# Generated by Django 2.2.10 on 2026-03-15 10:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0033_auto_20220718_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='book_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_records', to='book.Book'),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='book_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='book',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 10, 56, 13, 746150, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('m', '男生'), ('f', '女生')], default='m', max_length=10),
        ),
    ]
