# Generated by Django 2.2.10 on 2026-04-08 02:51

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0034_auto_20260315_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=book.models.default_borrow_end_day),
        ),
    ]
