# Generated by Django 4.2.30 on 2026-04-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0035_auto_20260408_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='open_or_close',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Closed'), (2, 'Pending Return')], default=0),
        ),
    ]
