# Generated by Django 4.2.30 on 2026-04-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0036_alter_borrowrecord_open_or_close'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='open_or_close',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Closed'), (2, 'Pending Return'), (3, 'Pending Borrow')], default=0),
        ),
    ]
